networks:
  services-network:
    driver: bridge

services:
  services-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "services-db"
    ports:
      - "1433:1433"
    # volumes: 
    #   - sqlsystem:/var/opt/mssql/
    #   - sqldata:/var/opt/sqlserver/data
    #   - sqllog:/var/opt/sqlserver/log
    #   - sqlbackup:/var/opt/sqlserver/backu[p
    environment:
      SA_PASSWORD: "dev@1234"
      ACCEPT_EULA: "Y"
    networks:
      - services-network

  rabbitmq-service:
    image: masstransit/rabbitmq
    container_name: rabbitmq-service
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - services-network

  cache-service:
    image: redis:6.2-alpine
    container_name: cache-service
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - services-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - services-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:5601
    networks:
      - services-network

  auction-service:
    build: 
      context: .
      dockerfile: ./Dockerfile.auctions
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__AuctionServiceDb=Server=services-db;Database=AuctionService;User=sa;Password=dev@1234;Trust Server Certificate=True;
      - ConnectionStrings__RedisConnection=cache-service:6379,password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - BackgroundService__ExecutionIntervalInMilliseconds=60000
      - RabbitMQ__Host=rabbitmq-service
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=auction-service
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ElasticConfiguration__ServiceName=auctions-service
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - services-db
      - rabbitmq-service
      - cache-service
      - elasticsearch

  bid-service: 
    build: 
      context: .
      dockerfile: ./Dockerfile.bids
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__BidServiceDb=Server=services-db;Database=BidService;User=sa;Password=dev@1234;Trust Server Certificate=True;
      - ConnectionStrings__RedisConnection=cache-service:6379,password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - RabbitMQ__Host=rabbitmq-service
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=bid-service
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ElasticConfiguration__ServiceName=bids-service
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - services-db
      - rabbitmq-service
      - cache-service
      - elasticsearch
      - auction-service
  
  api-gateway:
    image: yagooliverce/api-gateway:latest
    container_name: api-gateway
    ports:
      - "9000:80"
      - "11000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ReverseProxy__Clusters__auctions__Destinations__auctionApi__Address=http://auction-service/
      - ReverseProxy__Clusters__bids__LoadBalancingPolicy=RoundRobin
      - ReverseProxy__Clusters__bids__Destinations__bidApi__Address=http://bid-service/
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - bid-service
      - auction-service
volumes:
  # sqlsystem:
  # sqldata:
  # sqllog:
  # sqlbackup:
  elasticsearch-data:
