networks:
  services-network:
    driver: bridge

services:
  services-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "services-db"
    ports:
      - "1433:1433"
    volumes: 
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
    environment:
      SA_PASSWORD: "dev@1234"
      ACCEPT_EULA: "Y"
    networks:
      - services-network

  rabbitmq-service:
    image: masstransit/rabbitmq
    container_name: rabbitmq-service
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - services-network

  cache-service:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - services-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false # Disable security for ease of local testing
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - services-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:5601
    networks:
      - services-network

  # apm-server:
  #   container_name: apm-server
  #   image: docker.elastic.co/apm/apm-server:8.11.0
  #   ports:
  #     - "8200:8200"
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - apm-server.host=0.0.0.0:8200
  #     - apm-server.kibana.host=http://kibana:5601
  #     - output.elasticsearch.hosts=["http://elasticsearch:9200"]
  #   networks:
  #     - services-network

  auction-service:
    build:
      context: .
      dockerfile: Dockerfile.auctions
    # container_name: auction-service
    # ports:
    #   - "10090:80" # HTTP port
    #   - "9090:443"   # HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__AuctionServiceDb=Server=services-db;Database=AuctionService;User=sa;Password=dev@1234;Trust Server Certificate=True;
      - ConnectionStrings__RedisConnection=cache-service:6379,password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - BackgroundService__ExecutionIntervalInMilliseconds=60000
      - RabbitMQ__Host=rabbitmq-service
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=auction-service
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ElasticConfiguration__ServiceName=auctions-service
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - services-db
      - rabbitmq-service
      - cache-service
      - elasticsearch

  bid-service: 
    build:
      context: .
      dockerfile: Dockerfile.bids
    container_name: bid-service
    # ports:
    #   - "10091:80" # HTTP port
    #   - "9091:443"   # HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__BidServiceDb=Server=services-db;Database=BidService;User=sa;Password=dev@1234;Trust Server Certificate=True;
      - RabbitMQ__Host=rabbitmq-service
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__QueueName=bid-service
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - ElasticConfiguration__ServiceName=bids-service
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - services-db
      - rabbitmq-service
      - elasticsearch
  
  api-gateway:
    # image: api-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile.apigateway
    container_name: api-gateway
    ports:
      - "9000:80"
      - "11000:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ReverseProxy__Clusters__auctions__Destinations__auctionApi__Address=http://auction-service/
      - ReverseProxy__Clusters__bids__LoadBalancingPolicy=RoundRobin
      - ReverseProxy__Clusters__bids__Destinations__bidApi__Address=http://bid-service/
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./devcerts:/app/certs:ro
    networks:
      - services-network
    depends_on:
      - bid-service
      - auction-service
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"     # Expose HTTP
      - "443:443"   # Expose HTTPS (optional, requires certificates)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx configuration
      - ./nginx/certs:/etc/nginx/certs:ro # Mount for certificates (optional, see below)
    networks:
      - services-network
    depends_on:
      - auction-service
      - bid-service
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  cache:
    driver: local
  elasticsearch-data:
