name: deploy-auction-service

on:
  workflow_run:
    workflows: ["test-integration"]
    types:
      - completed
      
env:
  REGISTRY_IMAGE: yagooliverce/auction-service
  DOCKERFILE: ./Dockerfile.auctions
  DEPLOYMENT_NAME: auction service deploy
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build:
    if:  ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}"
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: ${{ env.REGISTRY_IMAGE }}:latest